version: "3.9"

services:
  ms2_postgres:
    image: postgres:15
    container_name: ms2_postgres
    environment:
      POSTGRES_USER: ms2
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ms2_accounts
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ms2_service:
    build: .
    container_name: ms2_service
    depends_on:
      - ms2_postgres
    environment:
      DB_HOST: ms2_postgres
      DB_PORT: 5432
      DB_NAME: ms2_accounts
      DB_USER: ms2
      DB_PASSWORD: secret
    ports:
      - "8080:8080"

volumes:
  postgres_data: