version: "3.9"

services:
  # =============================
  # 📦 Base de datos PostgreSQL
  # =============================
  ms2_postgres:
    image: postgres:15
    container_name: ms2_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-ms2}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_DB: ${DB_NAME:-ms2_accounts}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-ms2} -d ${DB_NAME:-ms2_accounts}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - ms-network
    restart: unless-stopped

  # =============================
  # ⚙️ Servicio principal MS2
  # =============================
  ms2_service:
    build: .
    container_name: ms2_service
    depends_on:
      ms2_postgres:
        condition: service_healthy
    environment:
      # Configuración general
      APP_PORT: ${APP_PORT:-8080}

      # Config DB
      DB_HOST: ${DB_HOST:-ms2_postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-ms2_accounts}
      DB_USER: ${DB_USER:-ms2}
      DB_PASSWORD: ${DB_PASSWORD:-secret}

      # 🔗 Integración con MS1 (Customer Service)
      MS1_BASE_URL: ${MS1_BASE_URL:-http://ms1-customer-service:3000/api}

      # 🔗 Clave compartida para validaciones MS3
      SERVICE_KEY_FOR_MS3: ${SERVICE_KEY_FOR_MS3:-changeme}

      # 🔒 CORS / Frontend permitido
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://localhost:3000}

    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - ms-network
    restart: unless-stopped

# =============================
# 🧱 Volúmenes persistentes
# =============================
volumes:
  postgres_data:

# =============================
# 🌐 Red compartida entre microservicios
# =============================
networks:
  ms-network:
    external: true
